### Configure which tests are run 
### provide only one of the options below to include/skip test list
### full test list and documentation available at https://bandit.readthedocs.io/en/latest/plugins/index.html

# (optional) list included tests here:
# tests: ['B201', 'B301']

# (optional) list skipped tests here:
# skips: ['B101', 'B601']